# Numpy

### fundamental library for scientific computing in Python. Provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. 

In [20]:
! pip install numpy

In [2]:
import numpy as np


In [8]:
# create array using numpy
# 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:
# 2D array
arr2 = np.array([1,2,3,4,5])
arr2 = arr2.reshape(1,5)
print(arr2)

[[1 2 3 4 5]]


In [17]:
arr2 = np.array([[1,2,3,4,5,6]])
arr2.shape

(1, 6)

In [18]:
arr2 = np.array([[1,2,3,4,5], [5,4,3,2,1]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [5 4 3 2 1]]


(2, 5)

In [19]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [21]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
print(arr2.dtype)

int64


In [28]:
arr1.itemsize  # size of array in bytes

8

### Numpy vectorized operatins

In [35]:
arr1 = np.array(([1,2,3,4,5]))
arr2 = np.array([10,20,30,40,50])

# element wise operations
print('Addition: ', arr1+arr2)
print('Substratction: ', arr1 - arr2)
print('Multiplication: ', arr1 * arr2)
print(('Division :', arr1/arr2))

Addition:  [11 22 33 44 55]
Substratction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
('Division :', array([0.1, 0.1, 0.1, 0.1, 0.1]))


### Universal functions

In [39]:
arr = np.array([1,2,3,4,5,6])

# square root
print(np.sqrt(arr))

# exponent
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### Array Slicing and Indexing

In [43]:
arr = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
print(arr[0][0])

1


In [53]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [55]:
arr[1:, 0:2]

array([[ 5,  6],
       [ 9, 10]])

In [59]:
# modify array elements

arr[0,0] = 100
print(arr[0,0])

100


In [60]:
arr [1:] = 100

In [61]:
print (arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
# stastical concepts -- Normalization
# to have mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data-mean)/std_dev
print('Data after Normalization: ')
print(normalized_data)

Data after Normalization: 
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [75]:
# Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data > 5)
print(data[data>5])
print(data[(data>5) & (data<9)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7 8]
